In [ ]:
import numpy as np


In [ ]:
a = np.array([1, 2, 3, 4])


In [ ]:
a

In [ ]:
a.ndim # dimensão

In [ ]:
a.shape # formato

In [6]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [7]:
b.shape

(2, 4)

In [8]:
b.strides # 32 bytes + 32 bytes (8 bits cada)

(32, 8)

In [9]:
b.dtype

dtype('int64')

In [10]:
b.T # matriz transposta / armazena por coluna, ao invés de por linhas

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [12]:
c = b.T
c

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [13]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
b[0, 0] = 0 # muda o indice 0,0 para 0 tanto no b quanto no c
b

array([[0, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
c

array([[0, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [17]:
b[0,0:2] # retorna linha 0, duas primeiras colunas

array([0, 2])

In [18]:
np.max(b) # maior valor

8

In [19]:
0.1 + 0.2 # diferente de 0.3 - soma de dois pontos flutuantes = aproximação

0.30000000000000004

In [20]:
np.allclose(0.1+0.2, 0.3) # retorna se o valor da soma é próximo = True

True

In [21]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [22]:
np.sum(b) # faz em sentido de linhas primeiro, depois colunas 1+2+3+4+5+6+7+8]

#.sum(axis=0) = soma as colunas e forma um array de 1 linha. 

#.sum(axis=1) = soma as linhas e forma uma coluna

36

In [24]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [25]:
a = np.arange(1,5).reshape(2,2) # transforma em 2 por 2
a

array([[1, 2],
       [3, 4]])

In [26]:
b = np.array([[1,0], [0,1]])
b

array([[1, 0],
       [0, 1]])

In [28]:
b = np.eye(2) # cria matriz identidade = tipo flutuante
b

array([[1., 0.],
       [0., 1.]])

In [30]:
a+b # soma cada elemento

array([[2., 2.],
       [3., 5.]])

In [32]:
a/b # possui zero, entao retorna um warning

<ipython-input-32-3f90ff39bd7d>:1: RuntimeWarning: divide by zero encountered in true_divide
  a/b # possui zero, entao retorna um warning


array([[ 1., inf],
       [inf,  4.]])

In [33]:
# bradcasting = quando os elementos não possuem um tamanho que é imediatamente compatível
# 
a/9 # faz uma matriz 2x2 de 9 e divide cada elemento

array([[0.11111111, 0.22222222],
       [0.33333333, 0.44444444]])

In [34]:
c = np.array([2,2])
c

array([2, 2])

In [37]:
a/c
# pega a matriz [2,2] e replica a linha que esta faltando. Para coluna é a mesma coisa.

array([[0.5, 1. ],
       [1.5, 2. ]])

In [39]:
a = np.array([1,2,3]).reshape(1,3)
a

array([[1, 2, 3]])

In [40]:
b = np.array([1,2, 3]).reshape(3,1)
b

array([[1],
       [2],
       [3]])

In [41]:
a*b # faz o bradcast nas informações faltando para ambos os casos. Preenche linhas e colunas faltantes. 
# 123 * 111
# 123   222
# 123   333

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [42]:
a @ b

array([[14]])

In [43]:
b @ a

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [44]:
a

array([[1, 2, 3]])

In [45]:
a.T

array([[1],
       [2],
       [3]])

In [48]:
a.T.shape

(3, 1)

In [53]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [54]:
a.T

array([[1, 3],
       [2, 4]])

In [55]:
a[1] # coluna é vista como linhas

array([3, 4])

In [56]:
a[1].shape

(2,)

In [57]:
a[:,1].shape

(2,)

In [59]:
a = np.arange(1,5).reshape(4,1)
a.shape # vetor armazenado em colunas

(4, 1)

In [60]:
a

array([[1],
       [2],
       [3],
       [4]])

In [62]:
a = np.arange(1,7)
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [63]:
a.reshape(-1, 1) # para dizer que tem 6 linhas e 1 coluna

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [65]:
a.reshape(-1,1).shape

(6, 1)

In [66]:
a[:]

array([1, 2, 3, 4, 5, 6])

In [67]:
a[:, np.newaxis] # força a criação de um novo eixo. 

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [68]:
a.shape

(6,)

In [71]:
a.reshape(1,-1).shape

(1, 6)

In [72]:
a[np.newaxis, :].shape

(1, 6)

In [73]:
# retornar para um vetor de linhas
# achatamento
b = a.reshape(-1,1)

In [74]:
a

array([1, 2, 3, 4, 5, 6])

In [75]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [76]:
b.flatten()

array([1, 2, 3, 4, 5, 6])

In [77]:
b.flatten().shape # volta para vetor em colunas

(6,)

In [78]:
b.reshape(-1) # volta a representação por linhas

array([1, 2, 3, 4, 5, 6])

In [79]:
b.reshape(-1).shape

(6,)

In [87]:
b = np.arange(1,9).reshape(2,4)

In [88]:
a = np.arange(1,13).reshape(3,4)

In [89]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [93]:
c = np.arange(1,7).reshape(3,2)
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [94]:
np.hstack((a,c))

array([[ 1,  2,  3,  4,  1,  2],
       [ 5,  6,  7,  8,  3,  4],
       [ 9, 10, 11, 12,  5,  6]])

In [97]:
np.hstack((a,c,c))

array([[ 1,  2,  3,  4,  1,  2,  1,  2],
       [ 5,  6,  7,  8,  3,  4,  3,  4],
       [ 9, 10, 11, 12,  5,  6,  5,  6]])

In [98]:
np.hstack([a,c]) # pode ser uma lista, ao invés de tupla

array([[ 1,  2,  3,  4,  1,  2],
       [ 5,  6,  7,  8,  3,  4],
       [ 9, 10, 11, 12,  5,  6]])

In [100]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [101]:
b = np.arange(1,5)

In [103]:
np.vstack([a,b]) 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [113]:
c = np.arange(1,4)

In [114]:
c

array([1, 2, 3])

In [115]:
np.hstack([a,c]) # dá errado, pois o numpy vai sempre ser guiado por linhas (é armazenado como linhas em memória)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [116]:
np.hstack([a,c.reshape(-1,1)]) # a solução é fazer assim

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  2],
       [ 9, 10, 11, 12,  3]])

In [117]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [118]:
b = np.arange(1,9).reshape(2,4)

In [119]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [120]:
np.vstack([a,b]) #vertical

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [122]:
x = np.vstack([a,b])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [123]:
np.vsplit(x, [3]) # quebrar a matriz na terceira linha

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]])]

In [124]:
np.vsplit(x, [3,4]) # quebra na terceira e na quarta linha

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]])]

In [127]:
c = np.arange(1,7).reshape(3,2)

In [128]:
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [129]:
y = np.hstack([a,c])

In [130]:
y

array([[ 1,  2,  3,  4,  1,  2],
       [ 5,  6,  7,  8,  3,  4],
       [ 9, 10, 11, 12,  5,  6]])

In [131]:
np.hsplit(y, [4]) # quebra na horizontal:

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[1, 2],
        [3, 4],
        [5, 6]])]

In [132]:
a = np.array([1, 2, 3, 4]).reshape(2,2)

In [133]:
a

array([[1, 2],
       [3, 4]])

In [134]:
np.tile(a, (2,3)) # repetição de a em duas entradas na primeira dimensao (2 linhas) e 3 entradas na segunda dimensão (3 colunas)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [138]:
b = np.repeat(a, 3, axis=1) # repetir 3x a primeira coluna, e 3x da segunda coluna
b

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [136]:
a.repeat(3, axis=1) # outra forma de fazer a operação anterior

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [139]:
b = np.repeat(b, 2, axis=0) # repete o primeiro elemento(linha) 2x, e depois o segundo elemento 2x também
b

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4],
       [3, 3, 3, 4, 4, 4]])

In [141]:
a = np.arange(1,16).reshape(3,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [142]:
np.delete(a, 1, axis=0) # remover a linha 1, no eixo 0

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [143]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [145]:
np.delete(a, [1, 3], axis=1) # remover a segunda e quarta colunas

array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15]])

In [146]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [148]:
# remover toda a parte central (num range) / intervalo aberto (4 exclusivo)
np.delete(a, slice(1,4), axis=1)

array([[ 1,  5],
       [ 6, 10],
       [11, 15]])

In [150]:
# inserção:
a = np.arange(1, 10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [152]:
np.insert(a, 1, 10, axis=0) # adiciona o 10 numa nova linha, posição 1

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [154]:
u = np.array([[1,5], [6,10], [11, 15]])
u

array([[ 1,  5],
       [ 6, 10],
       [11, 15]])

In [155]:
w = np.array([[2, 3, 4], [7, 8, 9], [12, 13, 14]])
w

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [157]:
# inserir na matriz u, na posição 1, a matriz w, dirigido por colunas
np.insert(u, [1], w, axis=1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [159]:
np.insert(w, [1,2], u, axis=1) # inserir a matriz u em duas posições de w
# a coluna 0 de u vai para a coluna 1 de w. 
# a coluna 1 de u vai para a coluna 3 de w
# [1,2] = são as posições dos componentes do eixo que eu especificar (no caso é coluna)

array([[ 2,  1,  3,  5,  4],
       [ 7,  6,  8, 10,  9],
       [12, 11, 13, 15, 14]])

In [162]:
a = np.arange(1,16).reshape(3,5)

In [163]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [167]:
np.append(a, np.ones(5).reshape(1,-1), axis=0)

# tentar sempre deixar no shape correto;


array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [168]:
np.append(a, np.ones(6).reshape(3,2), axis=1)

array([[ 1.,  2.,  3.,  4.,  5.,  1.,  1.],
       [ 6.,  7.,  8.,  9., 10.,  1.,  1.],
       [11., 12., 13., 14., 15.,  1.,  1.]])

In [169]:
np.pad(a,1)

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  0],
       [ 0,  6,  7,  8,  9, 10,  0],
       [ 0, 11, 12, 13, 14, 15,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

In [170]:
np.pad(a,1, constant_values=1)

array([[ 1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  2,  3,  4,  5,  1],
       [ 1,  6,  7,  8,  9, 10,  1],
       [ 1, 11, 12, 13, 14, 15,  1],
       [ 1,  1,  1,  1,  1,  1,  1]])

In [172]:
np.pad(a, ((0,0), (1,3))) # 0 no superior, no inferior, 1 a esquerda, 3 a direita

array([[ 0,  1,  2,  3,  4,  5,  0,  0,  0],
       [ 0,  6,  7,  8,  9, 10,  0,  0,  0],
       [ 0, 11, 12, 13, 14, 15,  0,  0,  0]])

In [173]:
# convolução = multiplicação elemento elemento
# feito filtros para ser multiplicados e ir deslizando de acordo com o tamanho

In [174]:
np.max(a)
#a.max()

15

In [175]:
np.std(a) # desvio padrão

4.320493798938574

In [176]:
np.var(a) # variancia

18.666666666666668

In [177]:
a.max() # valor em todos os eixos

15

In [178]:
np.max(a, axis=0) # valores máximos guiados por linha

array([11, 12, 13, 14, 15])

In [179]:
np.max(a, axis=1) # guiado por colunas

array([ 5, 10, 15])

In [181]:
np.mean(a, axis=1)

array([ 3.,  8., 13.])

In [182]:
np.mean(a, axis=0)

array([ 6.,  7.,  8.,  9., 10.])

In [184]:
np.argmax(a) # posição do maior elemento (ele conta por linhas, sequencialmente)

14

In [185]:
# fazer media de uma determinada linha
np.mean(a[1]) # da linha [1], por exemplo

8.0

In [187]:
np.argmax(a, axis=0) # posição de todos os elementos máximos, por linha

array([2, 2, 2, 2, 2])

In [188]:
np.argmin(a, axis=1)

array([0, 0, 0])

In [193]:
np.unravel_index(a.argmax(), a.shape) # preciso passar o numero e o shape daquela matriz
# linha 2, coluna 4 (contando a partir de 0)

(2, 4)

In [194]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [195]:
np.any(a>10)
# existe algum elemento'ij' tal que a'ij' > 10

True

In [196]:
np.any(a>13, axis=0)
# b'j'(coluna) existe um indice em linha maior do que 13

array([False, False, False,  True,  True])

In [197]:
np.any(a>13, axis=1)
#b'i'(linha) existe indice em coluna maior do que 13

array([False, False,  True])

In [198]:
np.sort(a, axis=0) # ordenar por linhas

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [199]:
np.sort(a, axis=1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

# Matriz de 3 dimensões

In [207]:
# np.arange(1,9).reshape(2,2,2) - z, y, x

a = np.array([[[0,0,0,0], [0,0,0,0]], [[1,1,1,1], [1,1,1,1]], [[2,2,2,2], [[2,2,2,2]]])

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (<ipython-input-207-67ff560cd3a5>, line 3)

In [205]:
# imagens = RGB = y, x, z
np.array([[[0,1,2], [0,1,2], [0,1,2], [0,1,2]], [[0,1,2], [0,1,2], [0,1,2], [0,1,2]]]).shape # y, x, z (R, G, B)

(2, 4, 3)

In [ ]:
# operação dstack = garante que o z seja mantido na ultima coordenada

# np.moveaxis(a, 0, 2) = mova o eixo 0 para a posição 2